PR: Add new blogpost on spyder 4.0 beta release
spyder-ide/website-spyder pull request #150
Opened 2019-05-19 12:19 UTC by goanpeca

2019-05-19 16:47 UTC, CAM-Gerlach commented on .gitignore
> +.DS_Store
Missing final EOL

2019-05-19 16:53 UTC, CAM-Gerlach commented
@goanpeca Thanks, review in work.

2019-05-19 20:35 UTC, CAM-Gerlach requested changes
I really like the personal perspective, and it was written pretty well. Just a few comments (EDIT: Well, maybe a *little* more than a few...but most of them are relatively minor and quick fixes and I implemented all of them as Github suggestions to make applying them easy for you):

* [x] Following the existing convention for blog URLs, this one should be ``release-spyder-4beta2``.
* [x] By convention of every other post, the ``pub_date``, ``category``, ``tags``, ``author``, and ``summary`` (in that rough order) is always at the top of the post, not the bottom. Furthermore, ``twitter_handle`` isn't a valid tag (or at least isn't implemented or used), and there isn't an obvious justification for banning comments on this post.
* [x] ~~I kept your order below to keep the review cleaner, but LSP should go first, before the dark theme (in the prose listing in the summary and the 4b2 release section, and in the order of the sections themselves) since it is the biggest "headline" change in this release.~~
* [x] I would suggest generally avoiding having blocks of multiple images with no intervening body text; I find it preferable to have images inline with the text and to illustrate/support what is described, as it really breaks up the flow. Images should support the text not overwhelm it (particularly considering their size). This is something to keep in mind when writing as well as selecting and placing images; break your writing into smaller chunks if necessary to accomadate images between them.
* [x] The code and docstring style prefs pane look almost identical except with careful examination. Given this is a quick overview and promotional highlight, not anything close to documentation, only one should be shown (maybe docstring style, since its new) since showing both looks repetitive and doesn't add anything visually.
* [x] Remember, alt text should be much more descriptive; it isn't just a title. Per W3C and other standards, it needs to adequately describe the image's content if the image is unavailable or the user cannot see it. Where practicable, I made suggestions inline to address this.
* [x] The PNGs are *enormous*, 2.3 MB in total; due to being 2880 x 1798 in size (4x the resolution they are displayed at even on a 1080p monitor) and not having been run with optipng as is stated in our contributing guide and elsewhere (I got > 50% reductions on each of the images). Therefore, I'd downsample them to 1440 x 899 (I'd suggest nearest neighbor, as in my testing it produces good enough results without unacceptable aliasing artifacts while preserving compression efficiency), and then ``optipng -o7`` them, which resulted in a final file size reduction of >5x with essentially identical quality for the end purpose.

For the future, with the change I made to Github's ``linguist`` library that handles display of different files, I'd *strongly* recommend breaking lines by sentences instead of hard-wrapping at an arbitrary column width. It makes Git diffs make much more sense, greatly reduces manual labor when typing and revising, and makes reviewing way less work and using Github's suggestions feature far easier since I can make suggestions at the sentence level instead of having to split them into arbitrary chunks to follow whatever the hard wrapping randomly happens to be. It also would reduce by several times the number of review comments, since many of the changes are spliced across arbitrary boundaries, and make for at most one comment per sentence.

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +working with [Spyder](https://github.com/spyder-ide/spyder/) maintenance and
This isn't strictly an error, but its much more idiomatic to use "on" to mean what you mean here; "with" has a somewhat different implication. Also, it is silly to link Spyder here since users are already on its main web site; I presume this is just because you copied and pasted your Quansight post but don't forget you should always link to our main site, Spyder-IDE.org, unless you have a strongly motivated reason to link to our Github instead (which I don't see here).

```suggestion
working on Spyder maintenance and 
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +title: Spyder 4.0 coming closer, beta2 is now available!
I kept your overall style, but fixed the comma splice (grammar error) and made it less awkward/unidiomatic

```suggestion
title: Spyder 4.0 takes a big step closer with the release of Beta 2!
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +***This blogpost was originally published on the [Quansight Labs website](http://labs.quansight.org/)***
Per the contributing standards, all URLs must be HTTPS if available, and this one is. Also, it looks better in just italic without the bold, IMO, but if you disagree change it back.

```suggestion
*This blogpost was originally published on the [Quansight Labs website](https://labs.quansight.org/)*
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +allow_comments: no
Is there a justified reason for this?

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> + It has been almost two months since I joined Quansight, last April, to start  working with Spyder maintenance and  development. So far, it has been a very exciting and rewarding journey under  the g
The summary should *not* just repeat the first paragraph, if at all possible, or readers end up reading it twice, and it also doesn't fit the same "we" expository tone that all the others (including Jitse's) do. Also, links do not work in the summary, at least on this version of the theme (I may have implemented in my overhauled version, can't remember, though its usually not a good idea anyway). Also, it has a bunch of double spaces for some reason. Therefore:

```suggestion
In the first of a new series of blog posts chronicling our final push toward the Spyder 4.0 release and the new features we've implemented along the way, we announce the release of the milestone Beta 2, which represents nearly a year of intense work on Spyder's completion/introspection/help/analysis architecture, dark theme, plot pane, autosave, and much more.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +It has been almost two months since I joined Quansight, last April, to start
In conventional English usage, "last April" would mean April *2018* in this context, and the comma'd parenthetical is awkward. I'm still not 100% happy with it (part of it is constrained by the arbitrary hard breaks, but I suggest

```suggestion
It has been almost two months since I joined Quansight in April, to start 
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +Before we describe the features that will be included in the release of Spyder
This detail is gratuitously unnecessary here.

```suggestion
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +4.0beta2, I would like to give a warm welcome to
```suggestion
First off, I would like to give a warm welcome to
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +who recently joined Quansight, and will be working with the Spyder team to
This is great news, but the comma isn't needed.

```suggestion
who recently joined Quansight and will be working with the Spyder team to
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +for more than two years and we are very excited to have his (almost)
The CAMma givth, and the CAMma taketh away...

```suggestion
for more than two years now, and we are very excited to have his (almost)
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +# Spyder 4.0 beta2 release!
Be consistent.

```suggestion
# Spyder 4.0 Beta 2 released!
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +Since August 2018, when the first Beta of the 4.x series was released, the
In general usage, beta is not a proper noun if used by itself (rather than as part of a proper noun like Spyder 4 Beta 2).

```suggestion
Since August 2018, when the first beta of the 4.x series was released, the
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +Spyder development team has been working really hard on its next release,
More idiomatic, pronoun matching, clean up sentence structure by removing Beta 2 since it isn't vital to name it again here.

```suggestion
Spyder development team has been working hard on our next release.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +4.0 Beta2. The past couple of months we added the long awaited dark theme
Its really been almost a year, a "couple" of months technically means "two" (though in modern usage, it can sometimes be used to mean about 3, or perhaps even 4). Also, fix grammar errors and syntactic issues. Uses semicolon for proper separation since other list elements incorporate multiple comma-separated elements.

```suggestion
Over the past year, we've implemented the long awaited full-interface dark theme;
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +for the entire interface, we switched our entire code completion and linting
Avoid repetitive/redundant "we"s, more idiomatic/less syntactically tortured

```suggestion
overhauled our entire code completion and linting architecture to use the
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +architecture to the
Moved above
```suggestion
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +[Language Server Protocol](https://microsoft.github.io/language-server-protocol/)
Needs comma

```suggestion
[Language Server Protocol](https://microsoft.github.io/language-server-protocol/),
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +which opens the door to support many other
Cleaned up syntax.

```suggestion
opening the door to supporting many other languages in the future;
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +programming languages, and we merged several other goodies!
It doesn't make sense to list only two of the three features explicitly named in the section headers here. Also, improved wording and syntax.

```suggestion
added a new Plots pane to view and manage the figures generated by your code;
and numerous other feature enhancements, bug fixes and internal improvements.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +## Dark Theme
You alternate between Title Case and Sentance case for titles; you should be consistent. Our other blog posts all use Sentence case, so you should presumably use that.

```suggestion
## Dark theme
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +This has been a
In general, the first line in this style of writing should not directly refer to the section title.

```suggestion
A full-interface dark theme has been a
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +[long awaited feature](https://github.com/spyder-ide/spyder/issues/2350)
```suggestion
[long awaited feature](https://github.com/spyder-ide/spyder/issues/2350),
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +and will be the default theme for this new version. Users can still select the
Doesn't actually directly say we implemented it (which falsely implies it was always there and just needed to be enabled without work on our part). Prefer you to users.

```suggestion
and is enabled by default in Spyder 4. You can still select the
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +traditional OS specific theme by going to the **Appearance** section in our
Clearly and explicitly state the exact preferences setting, and use the standard format adopted by our docs. Also, it is referred to in Spyder as the "Light" theme, not the "OS-specific" theme (which confuses it with the Qt window style and the Automatic setting), so that's how it should be referred to here.

```suggestion
light theme under  ``Preferences > Appearance`` by either choosing a light-background
syntax-highlighting scheme, or changing ``Interface theme`` to ``Light``.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +**Preferences** dialog.
See above.

```suggestion
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +This enhancement was enabled by the work of
Clarity/idiomatic

```suggestion
This enhancement was made possible by the work of
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +[Colin Duquesnoy](https://github.com/ColinDuquesnoy) and
Avoid double ``and``

```suggestion
[Colin Duquesnoy](https://github.com/ColinDuquesnoy),
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +to pursue the release of QDarkStyle 3.x, which will be using the
Highlight that ``QtSASS`` is developed under our own umbrella.

```suggestion
to pursue the release of QDarkStyle 3.x, which will be using Spyder's
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +[qtsass](https://github.com/spyder-ide/qtsass/)
Proper caps

```suggestion
[QtSASS](https://github.com/spyder-ide/qtsass/)
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +A picture is worth a thousand words, so without further ado, here it is:
This just adds further ado about nothing :)

```suggestion
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +
This would be a great place to show a screenshot of that new pane.

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +![Spyder Dark style](spyder-qdarkstyle.png)
In the screenshot itself, I would suggest including more than just the few default panes, the console with no content at all and tons of empty, useless space.

Alt text should be more descriptive; it isn't just a title. Remember, it needs to adequately describe the image's content if the image is unavailable or the user cannot see it.

```suggestion
![Screenshot of the Spyder main window with default panes, with the dark theme applied across the entire interface](spyder-qdarkstyle.png)
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +## Language Server Protocol (LSP) implementation
Acronyms should not be defined in titles/headers. Also, verbiage tweak.

```suggestion
## Language Server Protocol architecture
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +The LSP was created by Microsoft for Visual Studio Code to standardize the
Following the above, syntax cleanup

```suggestion
The Language Server Protocol (LSP) was created by Microsoft for Visual Studio Code to standardize how
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +way in which development tools (i.e. editors and IDEs) communicate with
Following the above, swap i.e. for e.g. since other development tools can use it.

```suggestion
development tools (e.g. editors and IDEs) communicate with
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +different programming languages. With this, as
Clarity

```suggestion
different programming languages. With LSP, as
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +[they](https://microsoft.github.io/language-server-protocol/) describe it:
The link is to their *description* of it, not who "they" are, so it needs to be inlined accordingly.

```suggestion
[they describe it](https://microsoft.github.io/language-server-protocol/):
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +>A single Language Server can be reused in multiple development
Style, logical breaks

```suggestion
> A single Language Server can be reused in multiple development tools,
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +tools, which in turn can support multiple languages with minimal effort.
From above.

```suggestion
which in turn can support multiple languages with minimal effort.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +Since our 4.0beta2 version, Spyder is now one of such development tools! We
Grammar, meaning, consistent naming, avoid word repetition, avoid annoying break.

```suggestion
As of Spyder 4 Beta 2, Spyder is now one of those tools!
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +developed our own client to communicate with any server that implements the
Following above, syntax

```suggestion
We developed our own client to communicate with any server that implements
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +architecture, and mouse hovers were added too (other LSP features, such as
Break this into sentences, fix syntax, mention docstring style analysis and name hover hints correctly.

```suggestion
architecture, and hover hints and docstring style analysis were added.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +signatures and docstring extraction were rewritten to take advantage of this
Put these in terms of the features the user is actually familiar with.

```suggestion
help generation, calltips, and real-time code/style analysis were rewritten to take advantage of this
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +workspace functionality, will come in future betas).
As above and add OTF completion so list isn't one item long.

```suggestion
Further LSP features, such as workspace functionality and on the fly completion, will come in future betas.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +as yapf and autopep8.
Following above, canonical capitalization is YAPF

```suggestion
YAPF and autopep8.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +betas we’ll also add the ability to use and configure code formatters such
Cleaner flow

```suggestion
betas we’ll also add the ability to use and configure code formatters like
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +<small>Code style preferences</small>
The ``<small>`` captions aren't showing up, since they are currently styled to be white for some reason (possibly fixed in the updated version of the theme with all the CSS cleanup I did, but not sure). I'm not sure captions are a good idea anyway, since in these sorts of blog posts images are generally used inline and support the text, but if you really want to do it that way, its your choice.

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +![Hover hint and calltips](spyder-hover-hint-calltip.png)
This should go directly after the paragraph ("As of Spyder 4 Beta 2") where it is discussed, and would break up this block. 

Also, please correct the alt text be more descriptive ("Screenshot of Spyder's Editor, showing a popup hint and a function calltip").

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +![Docstring style preferences](spyder-doc-prefs.png)
Eliminate one of these two, as discussed in the review summary.

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +We offer support to configure LSP servers  for other programming languages
Fix grammar errors, syntax issues and double space.

```suggestion
We support configuring LSP servers for additional, non-Python programming languages.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +as well. In the future we hope to include out-of-the-box support for
Following above, add needed comm, remove repeated word

```suggestion
In the future, we hope to include out-of-the-box LSP integration for
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +programming languages in the scientific computing spectrum, such as
Fix grammar, syntax, meaning, diction, clarity and repeated words

```suggestion
some of the most popular languages in the scientific computing space,
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +Fortran, Julia and C/C++.
Following above

```suggestion
including Fortran, Julia and C/C++.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +![Other languages](spyder-preferences-lsp.png)
Alt text

```suggestion
![Spyder Completion and Linting preferences pane, showing example PyLS servers configured for Go and Julia](spyder-preferences-lsp.png)
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +Following the steps and inspiration of RStudio, another well known IDE in the
Major syntactic cleanup, link Rstudio, remove awkward/unidiomatic verbiage

```suggestion
Similar to [RStudio](https://www.rstudio.com/) and other data science IDEs,
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +Data Science space, Spyder now includes a Plots viewer pane. Since beta2 plots
Following the above, fix syntax errors, and greatly improve semantics. Also, either give the actual name of the pane as a proper noun, or a descriptive name as a common noun, not a confusing mix of both.

```suggestion
Spyder now includes a Plots pane, allowing you to browse all figures created during a session.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +generated in every console will be displayed there, and the pane will be
This is really confusing; its not at all clear what its trying to say even to a core developer and native English writer/copyeditor like myself. Does it means that currently the plot pane shows all plots, but in the future it will only show the plots of the current console (motivating the suggested change below)? Or something else?

```suggestion
In Beta 2, the pane shows the plots from every console, but in the future will
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +updated automatically to only show the plots of the current one. Besides,
As above, avoid nasty split.

```suggestion
automatically display just those generated by the currently selected one.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +users will have the ability to browse the history of all plots generated in a
"Besides" is not correct here, simplify syntax, prefer "you" to "users", adjust semantics to discuss more distinct features

```suggestion
Beyond just viewing plots, you can easily zoom, save/export, copy and remove them.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +session.
See above.

```suggestion
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +![Other languages](spyder-plots.png)
Copy paste error, alt text.

Also, in order to actually show the main utility of the plot pane (allowing the user to easily browse between **multiple** plots), you *really* should have more than one displayed there or much of the point of it is lost. Also, you should scroll up your console so it isn't quite so empty.

```suggestion
![Spyder main window, showing a figure displayed in the plots pane](spyder-plots.png)
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +## And much more
Make this make a little more sense in context...still not super happy with it.

```suggestion
## But wait, there's more!
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +There are many more features that have been developed in the previous 10
Avoid repetition, better semantics/diction

```suggestion
There are numerous additional features we've added in the previous 10
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +1. **Autosave** files in the editor. With this Spyder will recover your
Everyone repeat after me: Thou shalt only use ***ordered*** lists for things that actually have an explicitly defined and meaningful ***order***. That's *why* they are called ordered lists after all, lol. Also, improve semantics, and fix grammar/ syntax issues.

```suggestion
* **Autosave** and **File Recovery** in the editor, so Spyder can restore your
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +unsaved files in case it crashes before you save them.
Clearer and more representative description

```suggestion
unsaved files in case it crashes or something else goes wrong.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +2. Dedicated **Sympy**, **Cython** and **Pylab** consoles. This will make it
```suggestion
* Dedicated **Sympy**, **Cython** and **Pylab** consoles, making it
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +3. OS level **window pane undocking**. This will allow users to easily
Prefer addressing the reader directly

```suggestion
* OS level **window pane undocking**, allowing you to easily
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +organize panes in different monitors.
Avoid repetition, correct syntax.

```suggestion
organize panes across different monitors.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +in our Dataframe viewer.
For proper parallelism, this one should have a short description like the others.

```suggestion
in our Dataframe viewer, making working with complex datasets much easier.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +## How can you help?
Make much more idiomatic/less syntactically tortured

```suggestion
## You can help!
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +If you are a Spyder user and would like to help us test this beta release, you
Remove redundant verbiage, improve semantics

```suggestion
If would like to help us test this beta release and try out the new features it offers,
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +can do so by installing it with conda, from our beta releases channel:
Add a lot of important details and suggestions to avoid many potential issues.

```suggestion
you can! You can install it with ``conda`` (if using Anaconda/Miniconda, as we recommend),
or with ``pip``; we suggest doing so in a new Conda env or ``virtualenv``/``venv``
so you can easily switch between your existing Spyder install and the Spyder 4 beta.
For example, to do so with ``conda``, enter the following at the Terminal/Anaconda prompt:
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +$ conda update qt pyqt
Following above

```suggestion
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +$ conda install spyder=4.0.0b2 --channel spyder-ide
Incorporating above suggestions

```suggestion
$ conda create --channel spyder-ide --name spyder-beta spyder=4.0.0b2
$ conda activate spyder-beta
$ spyder
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +directory for its beta versions, so you can easily switch between our stable
Avoid repeat and be more accurate

```suggestion
directory for its development versions, so you can easily switch between our stable
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +and beta releases without fearing of damage to your current installation.
Avoid grammar errors and more accurately describe the effect

```suggestion
and beta releases without worrying about one affecting the other.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +If you find any issues, you can report them on our
Avoid repeat

```suggestion
If you find any bugs, you can report them on our
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +[issues tracker](https://github.com/spyder-ide/spyder/issues).
Minor correction and important reminder

```suggestion
[issue tracker](https://github.com/spyder-ide/spyder/issues);
make sure to search for your error message or behavior before making a new one.
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +## Closing Remarks
Again, be consistent.

```suggestion
## Closing remarks
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +development on an awesome product such as Spyder. I would also like to thank
Improve verbiage, avoid repeat

```suggestion
development on an awesome project like Spyder. I am also grateful to our
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +the users, [contributors](https://github.com/spyder-ide/spyder/graphs/contributors)
Grammar fix

```suggestion
users, [contributors](https://github.com/spyder-ide/spyder/graphs/contributors)
```

2019-05-19 20:35 UTC, CAM-Gerlach commented on content/blog/spyder-4-beta2-release/contents.lr
> +make Spyder an awesome tool!
Avoid repeat, improve verbiage.

```suggestion
making Spyder amazing!
```

2019-05-19 20:47 UTC, CAM-Gerlach commented
@goanpeca Also, I strongly recommend mentioning our release schedule going forward (monthly releases per the last I've heard from @ccordoba12 ) and giving a rough date for Spyder 4 final (even if "before the end of the year").

2019-05-20 16:29 UTC, goanpeca commented
Thanks for the review @CAM-Gerlach

2019-05-20 18:13 UTC, ccordoba12 commented
Yeah, thanks a lot for the thorough review @CAM-Gerlach! This is almost ready, I have to update just one screenshot, but I'll do it tomorrow (it's very late here).

2019-05-20 20:30 UTC, CAM-Gerlach commented
Thanks @ccordoba12 for working on this while @goanpeca 's sick; I'll use that time to do a final review pass with any last suggestions.

2019-05-20 20:33 UTC, ccordoba12 commented
Ok, I applied most of your changes (with some minor modifications to very few of your suggestions). I only disagree with putting the LSP before the dark theme. Both are important but the dark theme "sells" better Spyder 4 than the LSP, in my opinion.

2019-05-20 20:39 UTC, CAM-Gerlach commented
@ccordoba12 Okay, my thinking was that since autocompletion and help issues seem to be the number one problem people have had with Spyder 3 such that people would be excited to see it resolved, but the dark theme does provide a much more visible and visual difference from Spyder 4. So if you think its better, then I'm fine keeping it (and its up to you and @goanpeca anyway, its ultimately a strategic judgement call).

2019-05-20 21:02 UTC, CAM-Gerlach reviewed
Just a few very minor things (for real this time), all Github suggestions. Also, one content addition I mentioned earlier separate from the review:

- [x] ~~I suggest discussing (in a sentence or two, in the closing remarks section) the current plan to release new betas at approximately one-month intervals, and a very rough estimate (e.g. before the end of the year) of the release date of Spyder 4.0 final.~~

2019-05-20 21:02 UTC, CAM-Gerlach commented on content/blog/release-spyder-4beta2/contents.lr
> +summary: In the first of a new series of blog posts chronicling our final push toward the Spyder 4.0 release and the new features we've implemented along the way, we announce the release of the miles
This ended up being a huge run on sentence without commas or parenthetical to break it up, my fault ofc. Much better version:

```suggestion
summary: We're excited to announce the release of the milestone Beta 2, which represents nearly a year of intense work on Spyder's completion/introspection/help/analysis architecture, dark theme, plot pane, autosave, and much more. This is the first of a new series of blog posts chronicling our final push toward the Spyder 4.0 release, and the new features we've implemented along the way, 
```

2019-05-20 21:02 UTC, CAM-Gerlach commented on content/blog/release-spyder-4beta2/contents.lr
> +4. Support for **[multi-indexes](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html)**
I must have missed changing this one to a bullet, sorry.

```suggestion
* Support for **[multi-indexes](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html)**
```

2019-05-20 21:02 UTC, CAM-Gerlach commented on content/blog/release-spyder-4beta2/contents.lr
> +Hover hint and calltips
This just shows up as awkward normal text underneath the screenshot, which looks out of place and not really like a caption. It isn't really necessary, since the surrounding text, the text in the screenshot and the alt text all describe and contextualize the screenshot better than these short captions anyway, rendering them unnecessary. The other screenshots don't have it; it was only there in the first place to break up the block of three screenshots that we reorganized to no longer be present.

```suggestion
```

2019-05-20 21:02 UTC, CAM-Gerlach commented on content/blog/release-spyder-4beta2/contents.lr
> +Docstring style preferences
As above.

```suggestion
```

2019-05-20 21:11 UTC, ccordoba12 commented
> I suggest discussing (in a sentence or two, in the closing remarks section) the current plan to release new betas at approximately one-month intervals, and a very rough estimate (e.g. before the end of the year) of the release date of Spyder 4.0 final.

This is still an open question, specially because the development state of the PyLS is unknown to us at this moment, and we need to fix several things on it.

So for now I don't want to make any estimates, but I hope the situation will be clearer for beta3 and then we could make this sort of statement.

2019-05-20 21:13 UTC, CAM-Gerlach commented
Okay, fair enough. Is there a rough idea of when Beta 3 will drop?

2019-05-20 21:14 UTC, ccordoba12 commented
> Okay, fair enough. Is there a rough idea of when Beta 3 will drop?

It should be ready the last week of June.

2019-05-20 21:15 UTC, ccordoba12 commented
I think this is ready. @CAM-Gerlach?

2019-05-20 21:15 UTC, CAM-Gerlach approved these changes

2019-05-20 21:16 UTC, CAM-Gerlach commented
> It should be ready the last week of June.

Okay, so hopefully by the end of July then :P

2019-05-20 21:16 UTC, CAM-Gerlach approved these changes
LGTM, thanks @ccordoba12 and @goanpeca !

2019-05-20 21:18 UTC, ccordoba12 commented
> Okay, so hopefully by the end of July then :P

As with beta2, I'll try to release with some sort of working state for the new projects features (if it's not finished). But that's far less complex than the LSP integration.

2019-05-20 21:23 UTC, ccordoba12 commented
@CAM-Gerlach, please merge when Travis goes green (I just merged a PR in the Sptder repo, so it should take half an hour).

@goanpeca, you can copy now the text and images to the Quansight Labs blog.

Thank you both for your work on this!

2019-05-20 21:26 UTC, ccordoba12 commented
@CAM-Gerlach, please don't move this production. I'll do it when the Quansight blog goes live.

2019-05-20 21:30 UTC, merged

2019-05-20 21:31 UTC, CAM-Gerlach commented
@ccordoba12 Looks like it was queued ahead of that, so its good to go now. It's live on ``develop``, ready to merge to production whenever you're ready. Thanks!