PR: Add debugger blogpost
spyder-ide/website-spyder pull request #185
Opened 2020-11-03 02:43 UTC by juanis2112

Added blogpost written by @impact27 about the new characteristics of the debugger.

<img width="1440" alt="Screenshot 2020-11-02 at 9 40 48 PM" src="https://user-images.githubusercontent.com/18587879/97945054-570f2200-1d54-11eb-85f9-7a499cd00881.png">

2020-11-03 21:48 UTC, CAM-Gerlach requested changes
Just a few minor textual comments, all as suggestions, and it LGTM once we merge #184 and rebase that in here. I can walk you through it once we're ready, thanks.

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +title: Debugger in Spyder 4
We should probably come up with a slightly more exciting title. Something like

```suggestion
title: All about Spyder 4's all-new debugger
```

would be a start.

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +summary: [IPython](https://ipython.org/) is a great improvement over the standard Python interpreter and brings many enhancements such as autocompletion and "magic" commands.
```suggestion
summary: [IPython](https://ipython.org/) is a great improvement over the standard Python interpreter, bringing many enhancements such as autocompletion and "magic" commands.
```

Avoid run-on sentence

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +(And believe me, I use this debugger a lot, and not only because I write code that might contain bugs :p
```suggestion
(And believe me, I use this debugger a lot, and not only because I write code that might contain bugs :p).
```

Mising paren

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +[IPython](https://ipython.org/) is a great improvement over the standard Python interpreter and brings many enhancements such as autocompletion and "magic" commands.
```suggestion
[IPython](https://ipython.org/) is a great improvement over the standard Python interpreter, bringing many enhancements such as autocompletion and "magic" commands.
```

As above

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +In this post, I will describe the debugger improvements we've already made in Spyder 4, as well as those I am working on for Spyder 4.2 and beyond, which are already under review in a bunch of Pull R
```suggestion
In this post, I will describe the debugger improvements we've already made in Spyder 4, as well as those that are already implemented or under review for Spyder 4.2 and beyond.
```

Update this given 4.2's imminent release, Avoid overly long sentence and clean up the syntax.

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +This can result useful if you don't know every documentation by heart!
```suggestion
This can result useful if you don't know every function's documentation by heart!
```

Add a necessary word here

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +When debugging code, a lot of time can be lost stepping through other Python packages . To avoid that, enable the new `Ignore Python libraries while debugging` option under the `Debug` menu.
```suggestion
When debugging code, a lot of time can be lost stepping through other Python packages.
To avoid that, enable the new `Ignore Python libraries while debugging` option under the `Debug` menu.
```

Fix period and line break

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +To solve this problem, all the single character Pdb commands will be available with a configurable keyboard shortcut.
```suggestion
To solve this problem, all the single character Pdb commands will be available with configurable keyboard shortcuts.
```

Match plural

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +I can have a variable named `step` and use it just as I would in the IPython shell!
```suggestion
Here, you can see I can have a variable named `step`, and use it just as I would in the IPython shell!
```

Prosify this caption

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +Interactive figures are great to zoom and pan.
```suggestion
For example, interactive figures are great to zoom and pan.
```

Make more sense outside of the context of a caption

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +With a Shift-click, you can set a conditional breakpoint that will only pause execution if an expression you write evaluates to `True`. This is very useful if you are debugging a loop and want to go
```suggestion
With a Shift-click, you can set a conditional breakpoint that will only pause execution if an expression you write evaluates to `True`.
This is very useful if you are debugging a loop and want to go to a specific iteration, for example!
```

Line break

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +The Spyder debugger is stopped at the breakpoint on line 385, which is highlighted.
```suggestion
Here, you can see the Spyder debugger is stopped at the breakpoint on line 385, which is highlighted.
```

Again, these need a little tweaking to make sense out of the context of a caption.

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +Usually while debugging it can be hard to tell from where the current function was invoked, and one must often step up a long chain of calls to figure it out.
```suggestion
Usually while debugging, it can be hard to tell from where the current function was invoked, and one must often step up a long chain of calls to figure it out.
```

Needs a comma

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +This might be ok but I haven't decided yet.
```suggestion
This might be okay, but I'm still figuring that out.
```

Use more positive phrasing

2020-11-03 21:48 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +Try out the new improvements of the Spyder debugger and let us know if they make your debugging easier!
```suggestion
Try out the new improvements in the Spyder debugger and let us know if they make your debugging easier!
```

Grammar/phrasing

2020-11-04 02:13 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +pub_date: 2020-11-06 20:00
```suggestion
pub_date: 2020-11-04 00:00
```

2020-11-04 04:35 UTC, ccordoba12 reviewed
Thanks a lot @juanis2112 for your help with this one!

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +The output is prettier (and easier to read) than plain black text!
```suggestion
The output is prettier (and easier to read) than plain black text! (the default in Spyder 3).
```

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +The completion and history for the debugger use the same code as the IPython console, so you should not notice any difference in behaviour.
```suggestion
Code completion and history for the debugger use the same functionality as the IPython console, so you should not notice any difference in behaviour.
```

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +This can result useful if you don't know every documentation by heart!
```suggestion
This can result useful if you don't know every library's documentation by heart!
```

Function is too specific.

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +This is better than getting `SyntaxError: unexpected EOF while parsing`.
```suggestion
This is better than getting `SyntaxError: unexpected EOF while parsing`, as in Spyder 3.
```

Clarify a bit that this was what you get before.

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +When debugging code, a lot of time can be lost stepping through other Python packages . To avoid that, enable the new `Ignore Python libraries while debugging` option under the `Debug` menu.
This option was removed from that menu and added to the IPython console preferences for 4.2:

![Selección_005](https://user-images.githubusercontent.com/365293/98048759-6053c980-1dfc-11eb-9dd5-61e9819abb27.png)

How should we handle that in the blogpost?

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +
```suggestion
However, this will only be required if you have a variable with the same name of the Pdb command you want to use.
In other words, variables will take precedence over Pdb commands and the use of the `!` prefix will be required only if a collision is detected between them.

```

This change was agreed on with Quentin after he wrote this post. I don't know if my second sentence is necessary or make things worse.

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +For example, the `step` command (`s`) can be triggered with `Alt+C`.
```suggestion
```

This no longer applies.

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +![Debugger](debugger-step.png)
This screenshot needs to be updated because things are different now.

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +I can have a variable named `step` and use it just as I would in the IPython shell!
I think we should change `shell` for `console` to have uniform terminology.

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +You'll be able to set this up for yourself under `Preferences` > `IPython Console` > `Startup` > `Run code while debugging`.
```suggestion
You'll be able to set this up for yourself under `Preferences` > `IPython Console` > `Debugger` > `Run code while debugging`.
```

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +![Debugger modules](debugger-modules.png)
This screenshot needs to be updated too because the message on top no longer applies.

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +First, if you use the `inline` backend, you can now enable plotting after each command by selecting the `Process execute events while debugging` option from the `Debug` menu.
This will be activated by default in 4.2 and present in `Preferences > IPython console > Debugger`. I'm not sure how to rephrase it though.

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +![Debugger plots](debugger-plots.png)
This screenshot needs to be updated.

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +![Debugger-autocomplete](debugger-autocomplete.png)
This screenshot needs to be redone.

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +![Debugger interactive plots](debugger-interactive-plots.png)
This screenshot needs to be updated.

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +## Spyder Editor integration
We should probably move this section to be before the improvements in 4.2 because it's new to Spyder 4 but not to 4.2.

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +![Debugger breakpoint](debugger-breakpoint.png)
I think we should add an additional screenshot above this one that shows people how to get Breakpoints in `View > Panes`.

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +Usually while debugging it can be hard to tell from where the current function was invoked, and one must often step up a long chain of calls to figure it out.
I think this should be moved to `The future` section below (because it's not even in master).

2020-11-04 04:35 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +![Frames Explorer](frames-explorer-.png)
This screenshot is missing.

2020-11-04 06:01 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +The output is prettier (and easier to read) than plain black text!
```suggestion
The output is prettier (and easier to read) than plain black text, as it was in Spyder 3!
```

Fix syntax and punctuation

2020-11-04 06:22 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +This is better than getting `SyntaxError: unexpected EOF while parsing`.
```suggestion
This is better than getting `SyntaxError: unexpected EOF while parsing`, as was the case in Spyder 3.
```

Clarify phrasing

2020-11-04 06:26 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +When debugging code, a lot of time can be lost stepping through other Python packages . To avoid that, enable the new `Ignore Python libraries while debugging` option under the `Debug` menu.
```suggestion
When debugging code, a lot of time can be lost stepping through other Python packages.
To avoid that, enable the new `Ignore Python libraries while debugging` option in Spyder's preferences under `IPython Console > Debugger > Debug`.
```

And maybe a screenshot of said preferences.

2020-11-04 06:28 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +
```suggestion
However, this will only be required if you have a variable with the same name as the Pdb command you want to use.
```

Fix grammar

>  I don't know if my second sentence is necessary or make things worse.

Your concerns are well-founded, IMO, It just restates the same thing, in more and more complicated words, so I suggest not adding it.

2020-11-04 06:29 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +For example, the `step` command (`s`) can be triggered with `Alt+C`.
So we're not adding the new keyboard shortcuts?

2020-11-04 06:34 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +First, if you use the `inline` backend, you can now enable plotting after each command by selecting the `Process execute events while debugging` option from the `Debug` menu.
```suggestion
First, if you use the `inline` backend, the `Process execute events while debugging` option in `Preferences > IPython console > Debugger` (on by defaults) enables plotting after each command.
```

Per the above request

2020-11-04 06:45 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +## Spyder Editor integration
So before Core Improvements, or after? As I understand, the core improvements are new, but it would be kinda of weird to not have "Core improvements" be first since it seems the most important. And I also see value in highlighting the most exciting new features first, rather than just whatever we happened to implement first, so idk

2020-11-04 06:47 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +![Debugger breakpoint](debugger-breakpoint.png)
We could show a wider screenshot for the breakpoints pane (right now its _super_ cramped and cropped in) with the Panes menu visible and the cursor over the pane.

2020-11-04 06:51 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +# The future
```suggestion
## The future
```

Neglected to fix this earlier, sorry

2020-11-04 06:51 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +
```suggestion



```

2020-11-05 04:41 UTC, juanis2112 commented on content/blog/spyder-debugger/contents.lr
> +I have `plt` everywhere!
```suggestion
```

2020-11-05 05:02 UTC, juanis2112 commented on content/blog/spyder-debugger/contents.lr
> +![Frames Explorer](frames-explorer-.png)
```suggestion
![Frames Explorer](frames-explorer.png)
```

2020-11-05 05:15 UTC, juanis2112 commented
@CAM-Gerlach and @ccordoba12 this is ready for a last review. @CAM-Gerlach I think that the title is a little bit confusing with the repeated "all". Can you try to suggest something simpler for it?

2020-11-05 14:33 UTC, CAM-Gerlach commented
I'm not sure what part of it you see as confusing; here repetition is used as the key rhetorical device ([Anaphora](https://en.wikipedia.org/wiki/Repetition_(rhetorical_device)), as is commonly done in titles. But I can certainly come up with something else, if we agree we don't like it. What do you think, @ccordoba12 ?

Here are some other options:

T0: Current version

```
All about Spyder 4's all-new debugger
```

T1: Something straightforward, if rather boring

```
New features in Spyder's debugger
```

T2: Something between T0 and T1

```
New features in Spyder 4's new debugger!
```

T3: Emphasizes the versions and progressive improvement, though a little more complex with the multiple versions

```
New debugger features in Spyder 4, 4.2 and beyond!
```

Whatever we decide on, I can implement when I do the rebase to avoid triggering an extra Travis build; as much as possible for the near future we need to minimize the number of pushes to branches with active PRs across the website, website theme, docs and docs theme repos (and any others that still use Travis) until we migrate them to Github Actions, as Travis will simply stop working on all of them once we hit our limit. Its also super slow now; I've had jobs wait in the build queue an hour or more. I can do the site and the theme soon but the docs are blocked on doctr until we can figure out something with that.

2020-11-05 21:40 UTC, impact27 commented
I made some minor changes to the text (https://github.com/spyder-ide/website-spyder/pull/185/commits/5696a90f7b8d155ff0038d08e47e674d7e7bff9a) otherwise looks good to me!

2020-11-05 21:56 UTC, ccordoba12 commented
Thanks @impact27 for your help!

2020-11-05 21:57 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +To avoid this, the Spyder 4.2 debugger will give precedence to Python expressions over Pdb commands. The addition of an exclamation mark prefix can be added to use a Pdb command explicitely. This is
```suggestion
To avoid this, the Spyder 4.2 debugger will give precedence to Python expressions over Pdb commands; prefixing an expression with an exclamation mark will explicitly run it as a Pdb command.
This matches how the IPython Console handles clashes between magic functions and Python expressions, and contrasts with the previous behavior, where Pdb commands took precedence.
You can toggle this under ``IPython Console > Debugger > Debug`` in Spyder's preferences.
```

@impact27 Fixed a number of typos and textual issues (repetition, passive voice, line breaks, choppy sentences, clarity etc) and I'm also pretty sure you mean giving precedence to

2020-11-05 22:06 UTC, impact27 commented on content/blog/spyder-debugger/contents.lr
> +To avoid this, the Spyder 4.2 debugger will give precedence to Python expressions over Pdb commands. The addition of an exclamation mark prefix can be added to use a Pdb command explicitely. This is
Thanks!

2020-11-05 22:20 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +To avoid this, the Spyder 4.2 debugger will give precedence to Python expressions over Pdb commands. The addition of an exclamation mark prefix can be added to use a Pdb command explicitely. This is
Sure thing, thanks for the clarifications in this section. If you're happy with this PR, feel free to approve, thanks.

2020-11-05 23:26 UTC, ccordoba12 commented on content/blog/spyder-debugger/contents.lr
> +title: All about Spyder 4's all-new debugger
```suggestion
title: New features in Spyder's debugger
```

2020-11-05 23:30 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +title: All about Spyder 4's all-new debugger
Already fixed, thanks.

2020-11-05 23:31 UTC, CAM-Gerlach commented on content/blog/spyder-debugger/contents.lr
> +To avoid this, the Spyder 4.2 debugger will give precedence to Python expressions over Pdb commands. The addition of an exclamation mark prefix can be added to use a Pdb command explicitely. This is
Implemented, thanks.

2020-11-05 23:33 UTC, ccordoba12 approved these changes
Thanks a lot @impact27 for your contribution! And @juanis2112 and @CAM-Gerlach for your help editing his content.

2020-11-05 23:35 UTC, CAM-Gerlach approved these changes
LGTM, I'll merge as soon as the tests pass.

2020-11-06 00:12 UTC, merged