PR: Add Spyder 2022 roadmap and proposals blogpost
spyder-ide/website-spyder pull request #206
Opened 2022-07-18 16:11 UTC by dalthviz

2022-07-22 02:10 UTC, CAM-Gerlach commented
I'll review this for content and meanwhile upgrade the pinned deps (including the Lektor version) and linting checks in another PR, which should fix the one unrelated linter issue.

2022-07-22 02:43 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +pub_date: 2022-07-18 20:00
Just as a reminder to whomever merges: Don't forget to update this!

2022-07-22 04:28 UTC, CAM-Gerlach requested changes
Thanks, @dalthviz , looks good overall. I just have some comments, all as suggestions, to improve the title and summary, and the grammar, phrasing, wording and punctuation of the body text.

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +For the last couple of months the Spyder team has been working on defining a roadmap and submitting grant proposals.
```suggestion
For the last couple of months, the Spyder team has been working on defining a new roadmap and submitting grant proposals to fund more features and improvements.
```

* Add compelling motivation for the grant proposals
* Avoid implying that we didn't have _any_ roadmap before
* Add missing comma

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +Now we are pleased to announce that we have a roadmap and we got two proposals accepted!
```suggestion
We are pleased to announce our roadmap for the rest of 2022, and that two proposals were funded!
```

* Clarify details and make clear that we're announcing the roadmap itself, not just the mere fact that we have one
* Fix grammar and phrasing issues
* Use more appropriate/specific diction on proposal acceptance
* Elide unneeded "Now"

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +Thinking on the importance of sharing a clear perspective of where the Spyder project is going and where most of our efforts will go for the next months, the Spyder team have created [an initial road
```suggestion
Considering the importance of sharing a clear perspective of where the Spyder project is going and where we will be focusing our efforts over the coming months, the team has created [an initial roadmap for the rest of 2022](https://github.com/spyder-ide/spyder/wiki/Roadmap).
```

* Use grammatically and semantically correct wording ("Thinking on" -> "Considering")
* Fix grammar (plural/singular agreement & "next [sic] months")
* Use more appropriate and idiomatic phrasing to describe focusing our efforts
* Avoid repetition of "Spyder"

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +The elements included in the roadmap were selected since we think those are important features and characteristics that have been mentioned in issues, face-to-face or virtual discussions, Stack Overf
```suggestion
We prioritized the highlighted features and enhancements based on input from issues, face-to-face and virtual discussions, Stack Overflow, social media and other feedback, to try to best capture the interests of our users and community.
```

* Rewrote to make much more focused and concise, and avoid a run-on sentence
* Reword to be more compelling
* Avoid passive voice and awkward phrasing

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +As part of making our roadmap achievable we took time to write and present proposals to different venues and organizations in the last couple of months.
```suggestion
To help make our roadmap achievable, we wrote and submitted proposals to several different venues and organizations in the last couple of months.
```

* Use simpler, shorter and more direct phrasing
* Use accurate diction ("present" -> "submit")
* Add missing comma

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +We have yet to hear back for some proposals to be granted but as mentioned we got two accepted!
```suggestion
While we have yet to hear back from some of them, two have already been funded!
```

* Fix several significant grammar issues
* Rewrite to be more focused, clear and concise
* Improve phrasing to be easier to understand

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +The first one we got was the [Google Season of Docs 2022 (GSoD 2022)](https://developers.google.com/season-of-docs/docs).
```suggestion
The first was for the [Google Season of Docs (GSoD) 2022)](https://developers.google.com/season-of-docs/docs).
```

* Simplify awkward, verbose and unnecessary phrasing 
* Avoid duplicate 2022

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +This grant will be focused mainly on improving and updating our users documentation for Spyder 5 Editor features.
```suggestion
This grant will be focused mainly on improving and updating our user documentation for Spyder 5's Editor features.
```

* Fix two small grammar/syntax errors

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +It also will help move forward our developers' documentation and make available tutorials and detailed information about our new plugin API.
```suggestion
It also will help enhance our developer documentation and add tutorials and detailed information covering our new plugin API.
```

* Fix grammar and wording issues

I'm not sure how much of this is still part of the current plan. @steff456 , can you confirm?

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +For more details about this grant you can check the [Spyder wiki page for the proposal](https://github.com/spyder-ide/spyder/wiki/GSoD-2022-Project-Proposal).
```suggestion
For more details, check out the [Spyder wiki page for the proposal](https://github.com/spyder-ide/spyder/wiki/GSoD-2022-Project-Proposal).
```

* Simplify awkward and wordy phrasing
* Fix grammar issue
* Add missing comma

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +In this grant we will be working on improving the installation experience for Spyder Windows users, by enabling the current standalone installers available to be auto-updatable and providing a way to
```suggestion
For this grant, we will be working on improving the installation experience for Windows users by making the standalone installers auto-updatable and providing a simpler way to install custom packages not bundled with the installers.
```

* Fix grammar/prepositions
* Tweak phrasing to be shorter, simpler and easier to understand
* Use more appropriate wording
* Fix comma usage

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +With this grant we were able to contract one new developer, Juan Sebastian Bautista, a recent Systems and Computing engineer graduate from Universidad de los Andes in Bogotá, Colombia. Juan Sebastian
```suggestion
With this grant, we were able to hire a new developer—Juan Sebastian Bautista, a recent graduate in systems and computing engineering from Universidad de los Andes in Bogotá, Colombia—who will implement these features over the next six months.
```

* Fix grammar and clarify phrasing around degree/graduation
* Set off introduction of Juan Sebastian into a parenthetical to improve flow
* Simplify redundant/verbose phrasing and be clearer and more concise
* Use more appropriate wording
* Add missing comma
* Fix capitalization of academic major

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +For more details about this grant you can check the [Spyder wiki page for the proposal](https://github.com/spyder-ide/spyder/wiki/NumFOCUS-Small-Development-Grant-2022).
```suggestion
For more details, see the [Spyder wiki page for the proposal](https://github.com/spyder-ide/spyder/wiki/NumFOCUS-Small-Development-Grant-2022).
```

* Greatly simplify redundant phrasing
* Fix grammar
* Vary the words a bit from the previous

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +We will be focusing our time as a project on pushing forward the accepted proposals and submitting new ones.
```suggestion
We will be focusing our efforts as a project on moving forward with the accepted proposals and submitting new ones.
```

* Fix grammar
* Use more appropriate words

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +On top of this we will try to get more feedback about the things that volunteers, users and community in general want to see in the future for Spyder and share the proposals progress relaunching the
```suggestion
On top of that, we will gather more feedback about what volunteers, users and the community at large want to see for Spyder in the future, and share the progress of the proposals in the relaunched [Spyder Community calls](https://github.com/spyder-ide/community#spyder-communitycalls).
```

* Rewrite to fix unclear and difficult to understand grammar and meaning in the last clause
* Fix various grammar and wording issues
* Use more appropriate diction
* Add missing comma

I'm not 100% sure what you intended to say at the end, but I tried to infer what I could of its meaning here.

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +As a side note we want to thank NumFOCUS and Google Season of Docs for granting us the funds to be able to work on these projects and start making our roadmap possible!
```suggestion
We would like to thank NumFOCUS and Google Season of Docs for granting us the funds to be able to work on these projects and making our roadmap possible!
```

* Use simpler and more appropriate phrasing
* Avoid missing comma

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +title: Spyder 2022 roadmap and new grants work
```suggestion
title: New 2022 roadmap and grant funding
```

* Emphasize that both are new
* Elide redundant "Spyder" (this is the Spyder blog)
* Use more appropriate and compelling word ("work" -> "funding")

2022-07-22 04:28 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +summary: A quick update on Spyder 2022 roadmap and proposals being worked on.
```suggestion
summary: We'd like to share our brand new roadmap for the rest of 2022, powered by the feedback of users like you. We're also excited to announce two new grants we've been awarded, which fund significant improvements to Spyder's Windows installers and user/developer documentation.
```

I've rewritten this to roughly match the length, tone and content of the other summaries, with a short paragraph describing the key points, while sounding compelling and enticing viewers to click through and read more.

2022-07-22 17:03 UTC, ccordoba12 reviewed
This is pretty nice blogpost, thanks @dalthviz!

I left a tiny suggestion for you, otherwise looks good to me.

2022-07-22 17:03 UTC, ccordoba12 commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +On top of that, we will gather more feedback about what volunteers, users and the community at large want to see for Spyder in the future, and share the progress of the proposals in the relaunched [S
```suggestion
On top of that, we will gather more feedback about what volunteers, users and the community at large want to see for Spyder in the future version 6, and share the progress of the proposals in the relaunched [Spyder Community calls](https://github.com/spyder-ide/community#spyder-communitycalls).
```

2022-07-22 18:16 UTC, CAM-Gerlach commented on content/blog/spyder-roadmap-proposals-2022/contents.lr
> +On top of that, we will gather more feedback about what volunteers, users and the community at large want to see for Spyder in the future version 6, and share the progress of the proposals in the rel
```suggestion
On top of that, we will gather more feedback about what volunteers, users and the community at large want to see for Spyder 6, and share the progress of the proposals in the relaunched [Spyder Community calls](https://github.com/spyder-ide/community#spyder-communitycalls).
```

Shorter, simpler and easier to read

2022-07-22 19:00 UTC, CAM-Gerlach commented
#207 updates the build system and pre-commit hooks, resolving the one failing check, and should be ready to merge. Then, you can rebase this on that and everything should be :heavy_check_mark: (tested and confirmed locally for builds and pre-commit).

2022-07-22 23:41 UTC, CAM-Gerlach commented
#207 is now merged, so this can be rebased and it should be good to go

2022-07-25 16:40 UTC, CAM-Gerlach submitted a review, later dismissed
LGTM, thanks @dalthviz . Just don't forget to update the data before merging.

2022-07-25 16:57 UTC, dalthviz commented
Done @CAM-Gerlach :+1:

2022-07-25 17:08 UTC, ccordoba12 approved these changes
Thanks @dalthviz! Really nice blogpost.

2022-07-25 17:36 UTC, ccordoba12 commented
I'm going to merge this one because @CAM-Gerlach already approved it.

2022-07-25 17:37 UTC, merged